project_id = "opiojltrlkpivowxfvrz"

[functions.import-nl-plaatsen]
verify_jwt = false

[functions.generate-routes]
verify_jwt = false

[functions.import-buitenland-steden]
verify_jwt = false

[functions.check-domain]
verify_jwt = false

[functions.sitemap]
verify_jwt = false

[functions.log-prijsberekening]
verify_jwt = false

[functions.send-smtp-email]
verify_jwt = false
